name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install tools
        uses: ./
        with:
          kubectl: latest
          go: latest
          yq: latest
          kustomize: latest
          helm: latest
          kubeseal: latest
          kubeval: latest
          conftest: latest
          kubeaudit: latest
          kubeconform: latest
          kyverno: latest
      - name: kubeval
        run: |
          kustomize build test/kustomize | kubeval --strict --ignore-missing-schemas
      - name: conftest
        run: |
          kustomize build test/kustomize | conftest test -p test/policy -
      - name: test installed tools
        run: |
          kubectl version --client
          go version
          jq --version
          yq --version
          kustomize version
          helm version --client
          kubeseal --version
          kubeval --version
          conftest --version
          kubeaudit version
          kubeconform -v
          kyverno version
